theme = "onedark"

[editor]
scrolloff = 10
mouse = true
middle-click-paste = true
scroll-lines = 3
line-number = "relative"
cursorline = false
cursorcolumn = false
continue-comments = true
auto-completion = true
path-completion = true
auto-format = true
preview-completion-insert = true
completion-trigger-len = 2
auto-info = true
true-color = false
bufferline = "multiple"
rulers = [88]
color-modes = false
text-width = 88
default-line-ending = "lf"
insert-final-newline = true
auto-pairs = false

[editor.lsp]
enable = true
display-messages = true
auto-signature-help = true
display-inlay-hints = true
display-signature-help-docs = true
snippets = true
goto-reference-include-declaration = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.file-picker]
hidden = false
follow-symlinks = true
ignore = true
git-ignore = false

[editor.auto-save]
focus-lost = false
after-delay.enable = false

[editor.search]
smart-case = true
wrap-around = true

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
tab = "→"

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

[editor.soft-wrap]
enable = true
max-wrap = 25

[editor.inline-diagnostics]
cursor-line = "info"

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
d = "delete_selection_noyank"
A-d = "delete_selection"
